[build]
  publish = "."
  functions = "netlify/functions"

# Removido o node_bundle antigo que deu erro e simplificado
[functions]
  included_files = ["database.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200